#!/usr/bin/env bash
set -euo pipefail

# self-heal-config.sh - self-healing Kconfig/defconfig stage.
#
# Vendored from CloudFox-INC/CloudFox-Kernel-Builder (build/self-heal-config.sh).
# Runs as POST_DEFCONFIG_CMDS (see build.config.portable, generated by
# build-kernel.yml) inside kernel/build build.sh, right after `make <DEFCONFIG>` and before `make <goals>`.
# It inherits build.sh's environment (ARCH, O=/OUT_DIR, LLVM, LLVM_IAS,
# toolchain PATH) - nothing else is required.
#
# What it does:
#   Derives the canonical config in a *pristine* scratch O= dir (never from
#   OUT_DIR/.config, which may carry builder-local CONFIG mods that must not
#   leak into the committed defconfig), compares it against the committed
#   arch/$ARCH/configs/$DEFCONFIG, and when the committed defconfig is
#   genuinely stale, repairs it and re-derives the effective config until a
#   stable fixed point is reached.
#
# Exit/state handling:
#   - already healthy           committed defconfig == canonical savedefconfig
#   - normalization detected    only symbol-order differences; same effective config
#   - repair performed          committed defconfig rewritten from canonical candidate
#   - repair verified           regenerated config converged to a fixed point
#   - repair rejected+restored  convergence failed; original restored, hard fail
#   - non-config failure        make/kbuild/toolchain error; hard fail

info() { printf '\033[1;34m[HEAL]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[HEAL]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[HEAL]\033[0m %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Env preconditions (all exported by build.sh before POST_DEFCONFIG_CMDS runs)
# ---------------------------------------------------------------------------
: "${ROOT_DIR:?ROOT_DIR not set - run under build/build.sh}"
: "${KERNEL_DIR:?KERNEL_DIR not set}"
: "${OUT_DIR:?OUT_DIR not set}"
: "${ARCH:?ARCH not set}"
: "${DEFCONFIG:?DEFCONFIG not set}"

# ---------------------------------------------------------------------------
# Toolchain args: must mirror what build.sh passes so LTO/CFI/SCS resolve the
# same way. LLVM=1 alone is NOT enough - LLVM_IAS=1 is required or HAS_LTO_CLANG
# turns false and CONFIG_LTO_CLANG_FULL/CONFIG_CFI_CLANG get dropped.
# ---------------------------------------------------------------------------
MAKE_ARCH_ARGS=()
if [ -n "${LLVM:-}" ]; then
    MAKE_ARCH_ARGS+=(LLVM="${LLVM}")
fi
if [ -n "${LLVM_IAS:-}" ]; then
    MAKE_ARCH_ARGS+=(LLVM_IAS="${LLVM_IAS}")
fi
# Bare-metal-only toolchains (CLANG_URL) cannot build host tools: build.sh's
# LLVM=1 path forces HOSTCC=clang and the generated host binaries SIGSEGV.
# self-heal-config runs its own `make` (kconfig/conf, fixdep, ...), so mirror
# the HOSTCC/HOSTCXX override build-kernel.sh passes to build.sh. The values
# come from build.config.cloudfox (CLOUDFOX_HOST_*), which build.sh does not
# clobber, unlike HOSTCC itself.
if [ -n "${CLOUDFOX_HOST_CC:-}" ]; then
    MAKE_ARCH_ARGS+=(HOSTCC="${CLOUDFOX_HOST_CC}")
fi
if [ -n "${CLOUDFOX_HOST_CXX:-}" ]; then
    MAKE_ARCH_ARGS+=(HOSTCXX="${CLOUDFOX_HOST_CXX}")
fi
MAKE_ARCH_ARGS+=(ARCH="${ARCH}")

run_make() { # <dir> <target>
    local dir=$1 target=$2
    ( cd "$ROOT_DIR/$KERNEL_DIR" && make "${MAKE_ARCH_ARGS[@]}" O="${dir}" "${target}" )
}

# map ARCH to the configs subdir (same logic as check_defconfig in _setup_env.sh)
cfg_arch=$ARCH
case "$cfg_arch" in
    x86_64|i386) cfg_arch=x86 ;;
esac

COMMITTED=${ROOT_DIR}/${KERNEL_DIR}/arch/${cfg_arch}/configs/${DEFCONFIG}
[ -f "$COMMITTED" ] || die "committed defconfig not found: $COMMITTED"

SCRATCH=$(mktemp -d "${OUT_DIR}/.self-heal.XXXXXX")
trap 'rm -rf "$SCRATCH"' EXIT

# ---------------------------------------------------------------------------
# 1) Derive the canonical config from a pristine source state.
#    We do NOT touch OUT_DIR/.config here - it may carry builder-local CONFIG
#    mods (fragments) that must never leak into the committed defconfig.
# ---------------------------------------------------------------------------
info "deriving canonical config in a pristine scratch dir"
run_make "$SCRATCH" "$DEFCONFIG"
run_make "$SCRATCH" savedefconfig
CANONICAL=$SCRATCH/defconfig
[ -f "$CANONICAL" ] || die "savedefconfig produced no output at $CANONICAL"

# ---------------------------------------------------------------------------
# 2) Compare. Textual inequality alone is NOT proof of brokenness: savedefconfig
#    normalizes symbol ordering, so a committed defconfig that only differs in
#    symbol placement still resolves to the identical effective .config.
# ---------------------------------------------------------------------------
if cmp -s "$COMMITTED" "$CANONICAL"; then
    info "already healthy: $DEFCONFIG matches canonical savedefconfig"
    exit 0
fi

# strip comments/blanks, keep the symbol/value grid, sort for ordering-insensitive
# compare. diff -q streams and short-circuits at the first difference, so the
# "differs" case never materializes both full grids.
if diff -q \
    <(grep -E '^CONFIG_[A-Za-z0-9_]+=' "$CANONICAL" | sort) \
    <(grep -E '^CONFIG_[A-Za-z0-9_]+=' "$COMMITTED" | sort) >/dev/null 2>&1; then
    info "normalization detected: $DEFCONFIG differs only in symbol ordering, effective config identical; no repair needed"
    exit 0
fi

# ---------------------------------------------------------------------------
# 3) Genuinely stale committed defconfig -> repair.
# ---------------------------------------------------------------------------
info "repair needed: $DEFCONFIG differs from canonical savedefconfig"

BACKUP="${COMMITTED}.self-heal-backup"
cp -a "$COMMITTED" "$BACKUP"
info "backed up the original defconfig"

cp -a "$CANONICAL" "$COMMITTED"
info "repair performed: committed defconfig rewritten from canonical candidate"

# ---------------------------------------------------------------------------
# 4) Invalidate the stale .config and re-derive the effective config from the
#    repaired defconfig until it converges (fixed-point check).
# ---------------------------------------------------------------------------
rm -f "${OUT_DIR}/.config" "${OUT_DIR}/.config.old"

for i in 1 2 3 4 5; do
    run_make "$OUT_DIR" "$DEFCONFIG" || {
        cp -a "$BACKUP" "$COMMITTED"
        die "repair rejected+restored: regeneration failed after rewriting $DEFCONFIG; original restored (non-config failure)"
    }
    run_make "$OUT_DIR" savedefconfig || {
        cp -a "$BACKUP" "$COMMITTED"
        die "repair rejected+restored: savedefconfig failed after rewriting $DEFCONFIG; original restored (non-config failure)"
    }
    if cmp -s "${OUT_DIR}/defconfig" "$CANONICAL"; then
        info "repair verified: regenerated config converged to canonical savedefconfig"
        rm -f "$BACKUP"
        # Commit the repaired defconfig into the local kernel tree so the
        # version string does not gain a -dirty suffix. Non-fatal: a non-git
        # tree or a failed commit only costs the dirty marker.
        if [ -d "$ROOT_DIR/$KERNEL_DIR/.git" ] && \
           git -C "$ROOT_DIR/$KERNEL_DIR" -c user.name="${GIT_BUILDER_NAME:-CloudFox Kernel Builder}" \
               -c user.email="${GIT_BUILDER_EMAIL:-builder@localhost}" \
               commit -q --only -m "cloudfox: self-heal $DEFCONFIG to canonical savedefconfig" -- \
               "arch/$cfg_arch/configs/$DEFCONFIG" 2>/dev/null; then
            info "committed repaired $DEFCONFIG (kernel version stays clean)"
        else
            warn "could not commit repaired $DEFCONFIG; kernel version may carry -dirty"
        fi
        exit 0
    fi
    info "iteration $i: regenerated config not yet stable; re-deriving"
done

cp -a "$BACKUP" "$COMMITTED"
rm -f "$BACKUP"
warn "repair rejected+restored: config did not converge to a fixed point"
warn "--- canonical (intended) ---"
diff -u "$COMMITTED" "$CANONICAL" >&2 || true
die "failed to converge: committed defconfig restored, build aborted; fix the source/config problem"
