#!/usr/bin/env bash
# stage-kleaf-fragments.sh - stage fragments for Kleaf's --defconfig_fragment.
#
# Unlike build.sh (bake into gki_defconfig + self-heal), Kleaf checks the
# BASE defconfig with stock check_defconfig (kernel_config.bzl POST hook),
# so the base must stay pristine. Fragments instead ride the order-insensitive
# merge_config.sh path via --defconfig_fragment=//common:builder_fragments.
#
# Resolves *.config fragments (sorted dirs, --extra-config temp file),
# validates + dedupes per-symbol, writes ONE combined file
# <kernel-dir>/builder_fragments.config, and appends a filegroup of that
# name to <kernel-dir>/BUILD.bazel (idempotent). No fragments = no-op
# (untouched tree, stock build).
#
# Usage:
#   stage-kleaf-fragments.sh --kernel-dir <common>
#     [--fragment-dir DIRorFILE]... [--extra-config "CONFIG_X=y,..."]
#     [--exclude "name,..."]
#
# A fragment dir may also carry an EXCLUDE file (one fragment name per
# line, # comments ok): features that cannot live on a tree are dropped
# for it without touching shared fragments. Same matching as --exclude
# (full name, minus .config, or core minus last -segment).
set -euo pipefail

KERNEL_DIR=""; FRAG_INPUTS=(); EXTRA_CONFIG=""; EXCLUDE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --kernel-dir) KERNEL_DIR="$2"; shift 2 ;;
    --fragment-dir) FRAG_INPUTS+=("$2"); shift 2 ;;
    --extra-config) EXTRA_CONFIG="$2"; shift 2 ;;
    --exclude) EXCLUDE="$2"; shift 2 ;;
    *) echo "stage-kleaf-fragments: unknown arg: $1" >&2; exit 2 ;;
  esac
done
[ -n "$KERNEL_DIR" ] || { echo "stage-kleaf-fragments: --kernel-dir required" >&2; exit 2; }
[ -f "$KERNEL_DIR/BUILD.bazel" ] || { echo "stage-kleaf-fragments: no BUILD.bazel in $KERNEL_DIR (not a Kleaf tree?)" >&2; exit 2; }

frags=""
for inp in ${FRAG_INPUTS[@]+"${FRAG_INPUTS[@]}"}; do
  if [ -d "$inp" ]; then
    for f in "$inp"/*.config; do
      [ -e "$f" ] || continue
      frags="$frags $f"
    done
  elif [ -f "$inp" ]; then
    frags="$frags $inp"
  else
    echo "stage-kleaf-fragments: fragment input not found (skipped): $inp" >&2
  fi
done
# shellcheck disable=SC2086
frags=$(printf '%s\n' $frags | sort -d | tr '\n' ' ')

# Per-directory EXCLUDE files (see header) feed the same drop logic.
for inp in ${FRAG_INPUTS[@]+"${FRAG_INPUTS[@]}"}; do
  [ -d "$inp" ] && [ -f "$inp/EXCLUDE" ] || continue
  while IFS= read -r line || [ -n "$line" ]; do
    # shellcheck disable=SC2086
    set -- $line
    [ $# -eq 0 ] && continue
    case "$1" in '#'*) continue ;; esac
    EXCLUDE="$EXCLUDE,$1"
    echo "stage-kleaf-fragments: exclude file adds: $1" >&2
  done <"$inp/EXCLUDE"
done

# Drop excluded names (full name, minus .config, or core minus last -segment).
if [ -n "$EXCLUDE" ]; then
  excl=${EXCLUDE//,/ }; keep=""
  # shellcheck disable=SC2086
  for frag in $frags; do
    [ -n "$frag" ] || continue
    name=$(basename "$frag"); core=${name%.config}; core=${core%-*}; drop=""
    # shellcheck disable=SC2086
    for e in $excl; do
      if [ "$name" = "$e" ] || [ "${name%.config}" = "$e" ] || [ "$core" = "$e" ]; then drop=1; break; fi
    done
    if [ -n "$drop" ]; then echo "stage-kleaf-fragments: excluded: $name" >&2
    else keep="$keep $frag"; fi
  done
  frags=$keep
fi

if [ -n "$EXTRA_CONFIG" ]; then
  lcf=$(mktemp); save_ifs=$IFS; IFS=,
  for line in $EXTRA_CONFIG; do
    [ -n "$line" ] || continue
    case "$line" in
      CONFIG_*=*|'# CONFIG_'*' is not set') printf '%s\n' "$line" >>"$lcf" ;;
      *) echo "stage-kleaf-fragments: ignoring non-CONFIG line: $line" >&2 ;;
    esac
  done
  IFS=$save_ifs
  [ -s "$lcf" ] && frags="$frags $lcf" || rm -f "$lcf"
fi

[ -n "${frags// /}" ] || { echo "stage-kleaf-fragments: no fragments, tree unchanged"; exit 0; }

OUT="$KERNEL_DIR/builder_fragments.config"
declare -A seen
{
  printf '# Generated by stage-kleaf-fragments.sh; consumed via\n# --defconfig_fragment=//common:builder_fragments (order-insensitive).\n'
  # shellcheck disable=SC2086
  for frag in $frags; do
    [ -f "$frag" ] || { echo "stage-kleaf-fragments: not found: $frag" >&2; exit 2; }
    bad=$(grep -nEv '^[[:space:]]*(#|$)|^CONFIG_' "$frag" || true)
    [ -z "$bad" ] || { echo "stage-kleaf-fragments: invalid lines in $frag:$bad" >&2; exit 2; }
    printf '# fragment: %s\n' "$frag"
    while IFS= read -r line || [ -n "$line" ]; do
      # `# CONFIG_X is not set` is a real Kconfig statement, not a comment.
      case "$line" in
        '') continue ;;
        '# CONFIG_'*' is not set') ;;
        '#'*) continue ;;
      esac
      case "$line" in
        *' is not set') sym=${line#\# }; sym=${sym%' is not set'}; cand="# ${sym} is not set" ;;
        CONFIG_*=*) sym=${line%%=*}; cand="${sym}=${line#*=}" ;;
        *) continue ;;
      esac
      # shellcheck disable=SC2076
      [[ -v 'seen[$cand]' ]] && continue
      printf '%s\n' "$line"
      seen["$cand"]=1
    done <"$frag"
  done
} >"$OUT"
echo "stage-kleaf-fragments: wrote $OUT"

if ! grep -q 'name = "builder_fragments"' "$KERNEL_DIR/BUILD.bazel"; then
  cat >>"$KERNEL_DIR/BUILD.bazel" <<'EOF'

# builder: extra defconfig fragments staged by tools/stage-kleaf-fragments.sh.
# Consumed via --defconfig_fragment=//common:builder_fragments.
filegroup(
    name = "builder_fragments",
    srcs = ["builder_fragments.config"],
)
EOF
  echo "stage-kleaf-fragments: filegroup appended to BUILD.bazel"
else
  echo "stage-kleaf-fragments: filegroup already present"
fi
